
# Absolute path
input     : "/.../PATH/fastqs" # provide path reads fastq files 
output    : "/.../PATH/output" # provide output directory path
 
db        : "/.../PATH/share/kraken_databases/viral_dba" # path to kraken viral datadase

ev_ref_genomes: "/blue/bphl-florida/share/evvp1_seqs/vp1_nucl01" # evNrv VP1 genes downloaded (building phylogenetic trees)

blastnevdb : "/.../PATH/evvp1_db/blastbd01/ev_vp1Gene_db"
blastpevdb : "/.../PATH/evvp1_db/blastbd01/ev_vp1Prot_db"
ev_ndbname : "EVvp1_genes"
ev_pdbname : "EVvp1_proteins"

vp1_metdt : "/.../.../PATH/EV_RV_vp1GenProt_v2ed.xlsx" # absolute path medata table  
mao4aln : "/.../.../PATH/clustal_align_nucleotide2.mao" # absolute path to  mega analysis option file for alignment
mao4tree : "/.../.../PATH/infer_ML_nucleotide.mao" # absolute path to mega analysis option file to build mega tree
vp1db : "/.../.../PATH/evvp1_db/VP1_k2customedDB/" # Kraken EV vp1 database